import {getCurrentUser} from '@/lib/auth/server';
import {findByInvite,findForUser,createGroup,saveGroup} from '@/db/repository';
import {consensus,projection,type Group,type Row,type Member} from '@/db/store';
export const dynamic='force-dynamic';
const reply=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
function name(v:unknown,max=40){return typeof v==='string'?v.trim().slice(0,max):'';}
const member=(uid:string,n:string):Member=>({uid,name:n,vote:null,goal:null,goalDays:null,steps:6000,workouts:2,ready:false});
export async function GET(req:Request){try{const u=await getCurrentUser();const url=new URL(req.url),invite=url.searchParams.get('invite');if(invite){const r=await findByInvite(invite);if(!r)return reply({error:'קישור ההזמנה לא נמצא. בקשי מהבנות קישור חדש.'},404);const g:Group=JSON.parse(r.state);return reply({authenticated:!!u,group:u?projection(r,u.userId):null,invitation:{name:g.name,count:g.members.length,started:!!g.start}});}
if(!u)return reply({authenticated:false,group:null});const r=await findForUser(u.userId);return reply({authenticated:true,group:r?projection(r,u.userId):null});}catch(e){console.error('group read',e);return reply({error:'לא הצלחנו לטעון את הקבוצה. נסי שוב בעוד רגע.'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==(process.env.APP_ORIGIN||new URL(req.url).origin))return reply({error:'בקשה לא מורשית'},403);const user=await getCurrentUser();if(!user)return reply({error:'התחברי כדי לשמור את המקום שלך בקבוצה.'},401);const uid=user.userId;const b=await req.json() as Record<string,unknown>;if(b.action==='create'){const n=name(b.name),title=name(b.title,60);if(!n||!title)return reply({error:'צריך למלא שם ושם קבוצה.'},400);const existing=await findForUser(uid);if(existing)return reply({group:projection(existing,uid)});const r:Row={id:crypto.randomUUID(),invite:crypto.randomUUID().replaceAll('-',''),revision:0,state:JSON.stringify({name:title,owner:uid,members:[member(uid,n)],start:null,days:null})};const saved=await createGroup(r);return reply({group:projection(saved,uid)});}
for(let retry=0;retry<5;retry++){const r=await findByInvite(String(b.invite||''));if(!r)return reply({error:'הקבוצה לא נמצאה.'},404);const g:Group=JSON.parse(r.state);let me=g.members.find(m=>m.uid===uid);if(b.action==='join'){if(me)return reply({group:projection(r,uid)});if(g.start||g.members.length>=4)return reply({error:'הקבוצה כבר מלאה או שהסבב התחיל.'},409);const n=name(b.name);if(!n)return reply({error:'מה השם שלך?'},400);g.members.push(member(uid,n));}else{if(!me)return reply({error:'אין לך גישה לקבוצה הזאת.'},403);if(g.start)return reply({error:'הסבב כבר התחיל, היעדים נעולים לסבב הזה.'},409);if(b.action==='vote'){const days=Number(b.days);if(![30,60,90].includes(days))return reply({error:'בחרי 30, 60 או 90 ימים.'},400);me.vote=days;}else if(b.action==='goals'){const d=consensus(g);if(!d)return reply({error:'קודם כולן צריכות להסכים על מספר הימים.'},409);const goal=Number(b.goal),steps=Number(b.steps),workouts=Number(b.workouts);if(b.goal===null||b.goal===undefined||b.goal===''||!Number.isFinite(goal)||goal<0||goal>100||!Number.isInteger(steps)||steps<1000||steps>30000||!Number.isInteger(workouts)||workouts<0||workouts>7)return reply({error:'בדקי את היעדים: צעדים בין 1,000 ל־30,000 ואימונים בין 0 ל־7.'},400);Object.assign(me,{goal,goalDays:d,steps,workouts,ready:true});}else if(b.action==='start'){if(g.owner!==uid)return reply({error:'רק פותחת הקבוצה יכולה להתחיל את הסבב.'},403);const d=consensus(g);if(!d||!g.members.every(m=>m.ready&&m.goalDays===d))return reply({error:'מחכות שארבעתכן תאשרו משך ויעדים.'},409);const tomorrow=new Date(Date.now()+86400000);g.start=tomorrow.toLocaleDateString('en-CA',{timeZone:'Asia/Jerusalem'});g.days=d;}else return reply({error:'פעולה לא מוכרת.'},400);}
if(await saveGroup(r,g))return reply({group:projection({...r,state:JSON.stringify(g),revision:r.revision+1},uid)});}
return reply({error:'הקבוצה התעדכנה תוך כדי. נסי שוב.'},409);}catch(e){console.error('group write',e);return reply({error:'השמירה לא הצליחה. הפרטים שלך נשארו כאן, נסי שוב.'},503);}}
