'use client';
import {useCallback,useEffect,useState} from 'react';
import {Heart,ArrowLeft,ArrowRight,Users,LockKeyhole,Check,Copy,Share2,Footprints,Dumbbell,Target,CalendarDays,LoaderCircle,House,ChartNoAxesCombined} from 'lucide-react';
import {Button} from '@/components/ui/button';
import SignIn from './sign-in';
import {authClient} from '@/lib/auth/client';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Group={revision:number;id:string;invite:string;name:string;isOwner:boolean;start:string|null;days:number|null;consensus:number|null;canStart:boolean;groupGoal:number;me:{name:string;vote:number|null;goal:number|null;goalDays:number|null;steps:number;workouts:number;ready:boolean};members:{id:number;name:string;isMe:boolean;isOwner:boolean;vote:number|null;ready:boolean}[]};
type State={authenticated:boolean;group:Group|null;invitation?:{name:string;count:number;started:boolean}};
type Screen='welcome'|'create'|'join'|'lobby'|'goal'|'connection'|'movement'|'home';
export default function DietApp(){
const [data,setData]=useState<State|null>(null),[screen,setScreen]=useState<Screen>('welcome'),[invite,setInvite]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[person,setPerson]=useState(''),[title,setTitle]=useState('האחיות והגיסה'),[goal,setGoal]=useState(''),[steps,setSteps]=useState('6000'),[workouts,setWorkouts]=useState('2'),[joinLink,setJoinLink]=useState('');
const g=data?.group;
const apply=useCallback((group:Group)=>{setData({authenticated:true,group});setInvite(group.invite);window.history.replaceState({},'',`/?invite=${group.invite}`);if(group.start)setScreen('home');},[]);
const refresh=useCallback(async(code:string,initial=false)=>{try{const res=await fetch('/api/group'+(code?'?invite='+encodeURIComponent(code):''),{cache:'no-store'});const d=await res.json() as State & {error?:string};if(!res.ok)throw Error(d.error);setData(current=>current?.group&&d.group?.id===current.group.id&&d.group.revision<current.group.revision?current:d);if(d.group){setInvite(d.group.invite);if(initial){setScreen(d.group.start?'home':'lobby');setPerson(d.group.me.name);}else if(d.group.start)setScreen('home');}else if(initial&&code)setScreen('join');if(initial)setError('');}catch(e){setError(e instanceof Error?e.message:'לא הצלחנו להתחבר. נסי שוב.');}},[]);
useEffect(()=>{const code=new URLSearchParams(location.search).get('invite')||'';setInvite(code);void refresh(code,true);},[refresh]);
useEffect(()=>{if(!g||g.start)return;const id=setInterval(()=>{if(document.visibilityState==='visible')void refresh(g.invite)},4000);return()=>clearInterval(id)},[g?.invite,g?.start,refresh]);
async function action(actionName:string,values:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');setNotice('');try{const res=await fetch('/api/group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:actionName,invite,...values})});const d=await res.json() as {group:Group;error?:string};if(!res.ok)throw Error(d.error);apply(d.group);return d.group as Group;}catch(e){setError(e instanceof Error?e.message:'השמירה לא הצליחה. נסי שוב.');}finally{setBusy(false)}}
useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();try{ctx.registerTool({name:'start_group_creation',title:'פתיחת מסך הקמת קבוצה',description:'Opens the group creation form. Does not create a group.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');if(g)throw Error('Already in a group');setScreen('create');return {screen:'create',created:false}}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort()},[g]);
const url=()=>`${location.origin}/?invite=${g?.invite||invite}`;
async function share(){try{if(navigator.share){await navigator.share({title:'ממחר דיאטה',text:`בואי לקבוצה שלנו: ${g?.name} 💚`,url:url()});}else await copy()}catch(e){if((e as Error).name!=='AbortError')setNotice('אפשר להעתיק את הקישור ולשלוח לבנות.')}}
async function copy(){try{await navigator.clipboard.writeText(url());setNotice('הקישור הועתק. עכשיו שולחת לבנות 💚')}catch{setNotice('לחצי לחיצה ארוכה על הקישור כדי להעתיק אותו.')}}
function editGoals(){if(!g)return;setGoal(g.me.goal===null?'':String(g.me.goal));setSteps(String(g.me.steps));setWorkouts(String(g.me.workouts));setScreen('goal');setError('')}
const back=()=>{setError('');setScreen(g?'lobby':'welcome')};
async function signedIn(){await refresh(invite,true);}
async function signOut(){if(busy)return;setBusy(true);try{const result=await authClient.signOut();if(result.error)throw Error();window.location.assign('/');}catch{setError('לא הצלחנו להתנתק. נסי שוב.');setBusy(false);}}
const submitButton=(text:string)=><Button className="primary" disabled={busy}>{busy?<LoaderCircle className="spinner"/>:text}{!busy&&<ArrowLeft size={18}/>}</Button>;
const members=()=>g&&<div>{g.members.map(m=><div className="member" key={m.id}><span className="avatar">{m.name.slice(0,1)}</span><div className="info"><strong>{m.name}{m.isMe?' · את':''}</strong><div className="mini muted">{m.isOwner?'פותחת הקבוצה':m.ready?'היעדים האישיים נשמרו':'איתנו במסע'}</div></div><span className="badge">{m.ready?'מוכנה ✓':m.vote?`${m.vote} ימים`:'הצטרפה ✓'}</span></div>)}{Array.from({length:4-g.members.length},(_,i)=><div className="member" key={'empty'+i}><span className="avatar" style={{background:'#f1eee8',color:'#87908a'}}>+</span><div className="muted">מקום שמור לעוד אחת משלנו</div></div>)}</div>;
return <main className="app"><header className="topbar"><span className="mark"><Heart size={23}/></span><div><strong>{g?.name||'ממחר דיאטה'}</strong><small>{g?`${g.members.length} מתוך 4 משתתפות`:'הפעם מתחילות יחד'}</small></div>{data?.authenticated&&<button className="signout" disabled={busy} onClick={()=>void signOut()}>יציאה</button>}</header>
{!data&&!error?<div className="loading"><LoaderCircle className="spinner"/><p>רגע, מתחברות…</p></div>:<>
{error&&<div style={{padding:'18px 24px 0'}}><p role="alert" className="error">{error}</p>{!data&&<Button className="secondary" onClick={()=>refresh(invite,true)}>מנסות שוב</Button>}</div>}
{notice&&<p role="status" className="success" style={{padding:'16px 24px 0'}}>{notice}</p>}
{screen==='welcome'&&<><div className="chat" aria-label="ככה זה מתחיל — שיחת דוגמה"><div className="bubble"><strong>אחותי</strong><p>טוב בנות… ממחר דיאטה? 😅</p><small>20:14</small></div><div className="bubble mine"><p>אני בפנים. אבל הפעם יחד 💚</p><small>20:15 ✓✓</small></div><div className="bubble"><strong style={{color:'#0b6155'}}>הגיסה</strong><p>סגרנו. מי פותחת קבוצה?</p><small>20:16</small></div><div className="bubble mine"><p>אני! שולחת לכן קישור 🙌</p><small>20:17 ✓✓</small></div></div><section className="opening"><h1>ממחר <span className="pink">דיאטה.</span></h1><p>קבוצות שמתחילות ביחד ומצליחות יחד</p><Button className="primary" onClick={()=>setScreen('create')}>יאללה, פותחת קבוצה <ArrowLeft/></Button><button className="textlink" onClick={()=>setScreen('join')}>כבר הזמינו אותך? הצטרפי לקבוצה</button></section></>}
{(screen==='create'||screen==='join')&&<section className="content stack"><button className="back" onClick={back}><ArrowRight size={18}/>חזרה</button><span className="eyebrow">{screen==='create'?'הצעד הראשון שלכן':'יש לך מקום איתנו'}</span><h1>{screen==='create'?'מי איתך הפעם?':data?.invitation?.name||'מצטרפת לבנות'}</h1><p className="muted">{screen==='create'?'את, שתי האחיות והגיסה. קבוצה אחת, מתחילות יחד.':data?.invitation?`${data.invitation.count} מתוך 4 כבר כאן.`:'הדביקי את הקישור ששלחו לך.'}</p>
{screen==='join'&&!data?.invitation?<form className="stack" onSubmit={e=>{e.preventDefault();try{const parsed=new URL(joinLink);const code=parsed.searchParams.get('invite');if(!code||! /^[a-f0-9]{32}$/.test(code))throw Error();setInvite(code);history.replaceState({},'',`/?invite=${code}`);void refresh(code,true)}catch{setError('זה לא נראה כמו קישור הזמנה. העתיקי את הקישור המלא.')}}}><label className="field">קישור הזמנה<input type="url" required value={joinLink} onChange={e=>setJoinLink(e.target.value)} placeholder="https://…" dir="ltr"/></label>{submitButton('מוצאת את הקבוצה')}</form>:data?.invitation&&(data.invitation.started||data.invitation.count===4)?<div className="card">הקבוצה מלאה או שהסבב התחיל. אם כבר הצטרפת, התחברי עם אותו אימייל.{!data.authenticated&&<SignIn onSuccess={signedIn}/>}</div>:!data?.authenticated?<SignIn onSuccess={signedIn}/>:<form className="stack" onSubmit={async e=>{e.preventDefault();const r=await action(screen==='create'?'create':'join',{name:person,title});if(r)setScreen('lobby')}}><label className="field">איך קוראים לך?<input autoComplete="given-name" required maxLength={40} value={person} onChange={e=>setPerson(e.target.value)} placeholder="השם שלך"/></label>{screen==='create'&&<label className="field">שם הקבוצה<input required maxLength={60} value={title} onChange={e=>setTitle(e.target.value)}/></label>}{submitButton(screen==='create'?'פותחת לנו קבוצה':'אני איתכן!')}</form>}<p className="note"><LockKeyhole size={17}/>היעד האישי שלך מופיע רק אצלך, גם פותחת הקבוצה לא רואה אותו.</p></section>}
{g&&screen==='lobby'&&<section className="content stack"><div><span className="eyebrow">הלובי שלכן</span><h1>{g.members.length<4?'מחכות לבנות 💚':'כולן כאן. איזה כיף!'}</h1></div><p className="muted">{g.members.length<4?'שולחת קישור, והן מצטרפות מהטלפון שלהן.':'בוחרות יחד כמה זמן, ואז כל אחת מגדירה את היעד שלה.'}</p><div className="card">{members()}</div>{g.members.length<4&&<div className="stack"><Button className="primary" onClick={share}><Share2 size={19}/>שולחת הזמנה לבנות</Button><div className="row"><Button className="secondary" variant="outline" onClick={copy}><Copy size={17}/>העתקת קישור</Button></div><span className="linkbox">{typeof window!=='undefined'?url():''}</span></div>}
<div className="card stack"><div className="row"><CalendarDays size={22}/><h2>כמה ימים ביחד?</h2></div><p className="muted mini">כל אחת בוחרת. מתקדמות רק כשארבעתכן מסכימות על אותו משך.</p><RadioGroup className="choices" dir="rtl" value={String(g.me.vote||'')} onValueChange={v=>void action('vote',{days:Number(v)})} disabled={busy} aria-label="משך הסבב">{[30,60,90].map(d=><label className="choice" key={d}><strong>{d}</strong><span>ימים</span><RadioGroupItem className="radio" value={String(d)} aria-label={`${d} ימים`}/></label>)}</RadioGroup><p className={g.consensus?'success':'mini muted'}>{g.consensus?<><Check className="inline-icon" size={17}/> כולן הסכימו על {g.consensus} ימים</>:g.me.vote?`${g.members.filter(m=>m.vote===g.me.vote).length} מתוך 4 בחרו ${g.me.vote} ימים`:'מה מתאים לך?'}</p></div>
{g.consensus&&<><Button className="primary" onClick={editGoals}>{g.me.ready?'היעדים שלי נשמרו · לצפייה ועריכה':'בוחרת את היעדים שלי'}<Target size={19}/></Button><p className="center mini muted">{g.members.filter(m=>m.ready).length} מתוך 4 סיימו לבחור יעדים</p>{g.isOwner?<><Button className="primary" disabled={!g.canStart||busy} onClick={()=>void action('start')}>כולן מוכנות? מתחילות מחר <ArrowLeft/></Button>{!g.canStart&&<p className="mini muted center">הכפתור ייפתח כשכולן יסיימו.</p>}</>:<p className="card green center">{g.canStart?'כולן מוכנות! מחכות שפותחת הקבוצה תתחיל את הסבב.':'ברגע שכולן מוכנות, פותחת הקבוצה תוכל להתחיל.'}</p>}</>}<p className="foot">מתעדכן אוטומטית כשמישהי מצטרפת או בוחרת.</p></section>}
{g&&['goal','connection','movement'].includes(screen)&&<section className="content stack"><button className="back" onClick={()=>setScreen(screen==='movement'?'connection':screen==='connection'?'goal':'lobby')}><ArrowRight size={18}/>חזרה</button><div className="stepbar" aria-label={`שלב ${screen==='goal'?1:screen==='connection'?2:3} מתוך 3`}><span className="done"/><span className={screen!=='goal'?'done':''}/><span className={screen==='movement'?'done':''}/></div>{!g.consensus?<div className="card stack"><h2>הבחירה הקבוצתית השתנתה</h2><p>מחכות שוב להסכמה של כולן על משך הסבב.</p><Button className="primary" onClick={()=>setScreen('lobby')}>חזרה ללובי</Button></div>:screen==='goal'?<><span className="private-label"><LockKeyhole size={17}/>רק את רואה את המספר הזה</span><h1>היעד שלך.<br/>בקצב שלך.</h1><p className="muted">מה יעד הירידה האישי שתרצי לשמור לסבב של {g.consensus} ימים?</p><form className="stack" onSubmit={e=>{e.preventDefault();setScreen('connection')}}><label className="field">יעד ירידה בק״ג<input type="number" inputMode="decimal" step="0.1" min="0" max="100" required value={goal} onChange={e=>setGoal(e.target.value)} placeholder="למשל 2"/><span className="helper">אפשר לבחור 0 ולהתמקד בתנועה ובהרגלים.</span></label><p className="note"><LockKeyhole size={17}/>זה יעד שאת בוחרת, לא המלצה אישית של האפליקציה.</p>{submitButton('ממשיכה ליעד המשותף')}</form></>:screen==='connection'?<><span className="eyebrow">כל אחת בשלה. כולנו ביחד.</span><h1>ארבעה יעדים.<br/>מסע אחד.</h1><div className="card green center stack"><Users style={{margin:'auto'}} size={32}/><div><div className="big-number">100%</div><p>מהיעדים האישיים של כולנו</p></div><p className="mini">היעד המשותף: כל אחת מתקדמת לעבר היעד שלה. לכל אחת חלק שווה בקבוצה.</p></div><p className="note"><LockKeyhole size={17}/>לא מציגות משקל, קילוגרמים או דירוג. המספר האישי שלך נשאר אצלך.</p><Button className="primary" onClick={()=>setScreen('movement')}>איתכן. עכשיו בוחרת תנועה <ArrowLeft/></Button></>:<><span className="eyebrow">הצעד האחרון לפני שמתחילות</span><h1>מה מתאים<br/>ליום־יום שלך?</h1><form className="stack" onSubmit={async e=>{e.preventDefault();const r=await action('goals',{goal,steps:Number(steps),workouts:Number(workouts)});if(r){setScreen('lobby');setNotice('היעדים שלך נשמרו. את מוכנה לסבב 💚')}}}><label className="field"><span><Footprints className="inline-icon" size={20}/> יעד צעדים ביום</span><input type="number" inputMode="numeric" min="1000" max="30000" step="100" required value={steps} onChange={e=>setSteps(e.target.value)}/></label><label className="field"><span><Dumbbell className="inline-icon" size={20}/> אימונים בשבוע</span><input type="number" inputMode="numeric" min="0" max="7" required value={workouts} onChange={e=>setWorkouts(e.target.value)}/></label><p className="helper">בוחרת מה שאפשרי לך. אלו יעדים אישיים, לא תחרות.</p>{submitButton('שומרת יעדים · אני מוכנה')}</form></>}</section>}
{g&&screen==='home'&&<section className="content"><div className="stack"><span className="eyebrow">{g.days} ימים, ארבע נשים, קבוצה אחת</span><h1>יצאנו לדרך,<br/>{g.me.name} 💚</h1><div className="card green row"><CalendarDays size={27}/><div><strong>מתחילות ב־{g.start?new Date(g.start+'T12:00:00').toLocaleDateString('he-IL'):''}</strong><p className="mini">הסבב שלכן נקבע. היעדים נשמרו.</p></div></div></div><Tabs defaultValue="plan" dir="rtl"><TabsList className="navtabs"><TabsTrigger value="plan"><House/>התכנית שלי</TabsTrigger><TabsTrigger value="data"><ChartNoAxesCombined/>הנתונים שלי</TabsTrigger><TabsTrigger value="group"><Users/>הקבוצה</TabsTrigger></TabsList><TabsContent value="plan"><div className="stack"><h2>הקצב שבחרת לעצמך</h2><div className="card metric"><div><h3>צעדים ביום</h3><span className="big-number">{g.me.steps.toLocaleString('he-IL')}</span></div><Footprints size={34}/></div><div className="card metric"><div><h3>אימונים בשבוע</h3><span className="big-number">{g.me.workouts}</span></div><Dumbbell size={34}/></div><p className="mini muted">זו התכנית שבחרת לסבב. מתחילות בצעד אחד בכל יום.</p></div></TabsContent><TabsContent value="data"><div className="stack"><span className="private-label"><LockKeyhole size={16}/>הנתונים האלה גלויים רק לך</span><div className="card stack"><h2>היעד האישי שלי</h2><div><span className="big-number">{g.me.goal}</span> ק״ג</div><p className="muted">יעד ירידה שבחרת ל־{g.days} ימים</p></div><div className="card"><p>צעדים ביום: <strong>{g.me.steps.toLocaleString('he-IL')}</strong></p><p>אימונים בשבוע: <strong>{g.me.workouts}</strong></p></div></div></TabsContent><TabsContent value="group"><div className="stack"><div className="card green"><h2>100% מהיעדים של כולנו</h2><p>כל אחת בקצב שלה. לכל אחת חלק שווה.</p></div><div className="card">{members()}</div><p className="note"><LockKeyhole size={17}/>היעדים האישיים נשארים פרטיים. כאן רואות רק מי איתנו.</p></div></TabsContent></Tabs></section>}
</>}
</main>}
